### ISSUE TITLE
nada

### ISSUE THREAD

**Issue by EntroFlux-Madman-X** [Hollings/discord-stable-diffusion#4]
not responding to commands

**Comment by Hollings** [comment]
I've pushed a handful of new updates today, including fixing the broken compatibility with the Automatic1111 webui. Try updating and rerunning `bot.py`. If that doesn't work, I'm happy to help if you can provide a more detailed report

**Comment by EntroFlux-Madman-X** [comment]
Hey  Hollings..did not mean to be a dick.....I worked on it for ages && got frustrated...thanks for your work

**Comment by Hollings** [comment]
No problem, the repo is a mess and poorly documented - you're good

**Comment by EntroFlux-Madman-X** [comment]
File "G:\fresh\bot.py", line 140, in <module>
    subprocess.Popen("webui.bat", cwd=config['WEB_UI_BATCH'], shell=True)
KeyError: 'WEB_UI_BATCH'

**Comment by Hollings** [comment]
🤦 my bad, I forgot to add that to the .env.example, pushing another update now

**Comment by EntroFlux-Madman-X** [comment]
dont' trip bro..you are helping me
I debug well but my raw code stinks

  File "G:\fresh\bot-generator.py", line 8, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'

**Comment by Hollings** [comment]
Try running `pip install -r requirements.txt` to install the required modules. If that doesn't work you can try to manually install it with `pip install python-dotenv`

**Comment by EntroFlux-Madman-X** [comment]
client = discord.Client(intents=discord.Intents.default()) add  that please

**Comment by EntroFlux-Madman-X** [comment]
Traceback (most recent call last):
  File "G:\rosy\bot.py", line 18, in <module>
    client = discord.Client()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by Hollings** [comment]
What version of discord.py are you on ` pip show discord.py`? I was having some trouble with SSL on the 2.x.x version and had to downgrade to `1.7.3`, but I think it's just an issue on my end

I'll see if I can get the repo to work on the latest discord.py though

**Comment by EntroFlux-Madman-X** [comment]
PS G:\rosy> pip show discord.py
Name: discord.py
Version: 1.7.3
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py
Author: Rapptz
Author-email:
License: MIT
Location: c:\users\chris\appdata\local\programs\python\python310\lib\site-packages
Requires: aiohttp
Required-by:

**Comment by EntroFlux-Madman-X** [comment]
https://slproweb.com/products/Win32OpenSSL.html will fix the ssl issue

**Comment by Hollings** [comment]
Ok, worked through the intents stuff and I have mine working on discord.py 2.0.1. try pulling the latest changes, rerunning `pip install -r requirements.txt` and running the bot. Make sure you have "MESSAGE CONTENT INTENT" enabled for your discord bot in the developer portal

**Comment by EntroFlux-Madman-X** [comment]
Traceback (most recent call last):
  File "G:\rosy\bot.py", line 148, in <module>
    subprocess.Popen("webui-user.bat", cwd=config['WEB_UI_DIR'], shell=True)
KeyError: 'WEB_UI_DIR'

  File "G:\rosy\bot.py", line 148, in <module>
    subprocess.Popen("webui-user.bat", cwd=config['WEB_UI_DIR'], shell=True)
KeyError: 'WEB_UI_DIR'

**Comment by EntroFlux-Madman-X** [comment]
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
PS G:\rosy>

**Comment by Hollings** [comment]
Try turning on the toggles under "Privileged Gateway Intents" in the discord developer portal "Bot" tab. 
![image](https://user-images.githubusercontent.com/3793509/196069738-a5672f16-be34-4627-a3dc-2f2b92c74dab.png)
![image](https://user-images.githubusercontent.com/3793509/196069754-7a82848d-6873-4740-b45c-c106b3a3df4b.png)

**Comment by EntroFlux-Madman-X** [comment]
I already had them  turned on...I am starting to think to think my
environment may need some attention.....maybe pip freeze && reinstall
everything
